# Generated by Django 5.0.4 on 2024-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Hamster', 'Hamster'), ('Perico', 'Perico'), ('Pez', 'Pez')], max_length=30)),
                ('genero', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
